// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzu2TcHVFN-PBYla-861yvXqmPm_9DJk',
    appId: '1:995451833005:web:72a54557ddba45bfb3d424',
    messagingSenderId: '995451833005',
    projectId: 'lihatlukis',
    authDomain: 'lihatlukis.firebaseapp.com',
    storageBucket: 'lihatlukis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAUqu-f9RSS4m7UNgAZNe6Kq1TgtquvEo',
    appId: '1:995451833005:android:9bfb4889f3dac917b3d424',
    messagingSenderId: '995451833005',
    projectId: 'lihatlukis',
    storageBucket: 'lihatlukis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2yplAfyWBylEhw5iMlSlyS0iwV-7Axp8',
    appId: '1:995451833005:ios:cd490e9c5747d2a4b3d424',
    messagingSenderId: '995451833005',
    projectId: 'lihatlukis',
    storageBucket: 'lihatlukis.appspot.com',
    iosBundleId: 'com.example.lihatLukis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2yplAfyWBylEhw5iMlSlyS0iwV-7Axp8',
    appId: '1:995451833005:ios:67f248ef78ad3c8fb3d424',
    messagingSenderId: '995451833005',
    projectId: 'lihatlukis',
    storageBucket: 'lihatlukis.appspot.com',
    iosBundleId: 'com.example.lihatLukis.RunnerTests',
  );
}
